services:
  auth_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      RDB: ${RDB}
      PGX: ${PGX}
      ADDR: ${ADDR}
      SECRET: ${SECRET}
    networks:
      - backend

networks:
  backend:
    external: true
    name: fool_backend
