services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      REDIS_ADDR: ${REDIS_ADDR}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      FOOL_AUTH_SERVICE_ADDR: ${FOOL_AUTH_SERVICE_ADDR}
    depends_on:
      - redis
    networks:
      - backend

  redis:
    image: redis:alpine
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
